name 'b_hardening'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures b_hardening'
long_description 'Installs/Configures b_hardening'
version '0.1.0'

depends 'os-hardening'
depends 'ssh-hardening' 
